// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: telemetry/v2/capture.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nevr.Telemetry.V2 {

  /// <summary>Holder for reflection information generated from telemetry/v2/capture.proto</summary>
  public static partial class CaptureReflection {

    #region Descriptor
    /// <summary>File descriptor for telemetry/v2/capture.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CaptureReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chp0ZWxlbWV0cnkvdjIvY2FwdHVyZS5wcm90bxIMdGVsZW1ldHJ5LnYyGh9n",
            "b29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvGh10ZWxlbWV0cnkvdjIv",
            "ZWNob19hcmVuYS5wcm90byKZAQoIRW52ZWxvcGUSLQoGaGVhZGVyGAEgASgL",
            "MhsudGVsZW1ldHJ5LnYyLkNhcHR1cmVIZWFkZXJIABIkCgVmcmFtZRgCIAEo",
            "CzITLnRlbGVtZXRyeS52Mi5GcmFtZUgAEi0KBmZvb3RlchgDIAEoCzIbLnRl",
            "bGVtZXRyeS52Mi5DYXB0dXJlRm9vdGVySABCCQoHbWVzc2FnZSKdAgoNQ2Fw",
            "dHVyZUhlYWRlchISCgpjYXB0dXJlX2lkGAEgASgJEi4KCmNyZWF0ZWRfYXQY",
            "AiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhYKDmZvcm1hdF92",
            "ZXJzaW9uGAMgASgNEjsKCG1ldGFkYXRhGAQgAygLMikudGVsZW1ldHJ5LnYy",
            "LkNhcHR1cmVIZWFkZXIuTWV0YWRhdGFFbnRyeRIzCgplY2hvX2FyZW5hGAog",
            "ASgLMh0udGVsZW1ldHJ5LnYyLkVjaG9BcmVuYUhlYWRlckgAGi8KDU1ldGFk",
            "YXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUINCgtn",
            "YW1lX2hlYWRlciJ4CgVGcmFtZRITCgtmcmFtZV9pbmRleBgBIAEoDRIbChN0",
            "aW1lc3RhbXBfb2Zmc2V0X21zGAIgASgNEjIKCmVjaG9fYXJlbmEYCiABKAsy",
            "HC50ZWxlbWV0cnkudjIuRWNob0FyZW5hRnJhbWVIAEIJCgdwYXlsb2FkIrkB",
            "Cg1DYXB0dXJlRm9vdGVyEhMKC2ZyYW1lX2NvdW50GAEgASgNEhMKC2R1cmF0",
            "aW9uX21zGAIgASgNEhUKDWZvb3Rlcl9vZmZzZXQYAyABKAQSMwoOa2V5ZnJh",
            "bWVfaW5kZXgYBCADKAsyGy50ZWxlbWV0cnkudjIuS2V5ZnJhbWVFbnRyeRIy",
            "CgtldmVudF9pbmRleBgFIAMoCzIdLnRlbGVtZXRyeS52Mi5FdmVudEluZGV4",
            "RW50cnkiOQoNS2V5ZnJhbWVFbnRyeRITCgtmcmFtZV9pbmRleBgBIAEoDRIT",
            "CgtieXRlX29mZnNldBgCIAEoBCJVCg9FdmVudEluZGV4RW50cnkSKwoKZXZl",
            "bnRfdHlwZRgBIAEoDjIXLnRlbGVtZXRyeS52Mi5FdmVudFR5cGUSFQoNZnJh",
            "bWVfaW5kaWNlcxgCIAMoDSr6BQoJRXZlbnRUeXBlEhoKFkVWRU5UX1RZUEVf",
            "VU5TUEVDSUZJRUQQABIcChhFVkVOVF9UWVBFX1JPVU5EX1NUQVJURUQQARIb",
            "ChdFVkVOVF9UWVBFX1JPVU5EX1BBVVNFRBACEh0KGUVWRU5UX1RZUEVfUk9V",
            "TkRfVU5QQVVTRUQQAxIaChZFVkVOVF9UWVBFX1JPVU5EX0VOREVEEAQSGgoW",
            "RVZFTlRfVFlQRV9NQVRDSF9FTkRFRBAFEiEKHUVWRU5UX1RZUEVfU0NPUkVC",
            "T0FSRF9VUERBVEVEEAYSHAoYRVZFTlRfVFlQRV9QTEFZRVJfSk9JTkVEEAoS",
            "GgoWRVZFTlRfVFlQRV9QTEFZRVJfTEVGVBALEiMKH0VWRU5UX1RZUEVfUExB",
            "WUVSX1NXSVRDSEVEX1RFQU0QDBIbChdFVkVOVF9UWVBFX0VNT1RFX1BMQVlF",
            "RBANEiYKIkVWRU5UX1RZUEVfRElTQ19QT1NTRVNTSU9OX0NIQU5HRUQQFBIa",
            "ChZFVkVOVF9UWVBFX0RJU0NfVEhST1dOEBUSGgoWRVZFTlRfVFlQRV9ESVND",
            "X0NBVUdIVBAWEhoKFkVWRU5UX1RZUEVfR09BTF9TQ09SRUQQHhIaChZFVkVO",
            "VF9UWVBFX1BMQVlFUl9HT0FMEB8SGgoWRVZFTlRfVFlQRV9QTEFZRVJfU0FW",
            "RRAoEhoKFkVWRU5UX1RZUEVfUExBWUVSX1NUVU4QKRIaChZFVkVOVF9UWVBF",
            "X1BMQVlFUl9QQVNTECoSGwoXRVZFTlRfVFlQRV9QTEFZRVJfU1RFQUwQKxIb",
            "ChdFVkVOVF9UWVBFX1BMQVlFUl9CTE9DSxAsEiIKHkVWRU5UX1RZUEVfUExB",
            "WUVSX0lOVEVSQ0VQVElPThAtEhwKGEVWRU5UX1RZUEVfUExBWUVSX0FTU0lT",
            "VBAuEiAKHEVWRU5UX1RZUEVfUExBWUVSX1NIT1RfVEFLRU4QLxIWChJFVkVO",
            "VF9UWVBFX0dFTkVSSUMQMkIUqgIRTmV2ci5UZWxlbWV0cnkuVjJiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Nevr.Telemetry.V2.EchoArenaReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Nevr.Telemetry.V2.EventType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nevr.Telemetry.V2.Envelope), global::Nevr.Telemetry.V2.Envelope.Parser, new[]{ "Header", "Frame", "Footer" }, new[]{ "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nevr.Telemetry.V2.CaptureHeader), global::Nevr.Telemetry.V2.CaptureHeader.Parser, new[]{ "CaptureId", "CreatedAt", "FormatVersion", "Metadata", "EchoArena" }, new[]{ "GameHeader" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nevr.Telemetry.V2.Frame), global::Nevr.Telemetry.V2.Frame.Parser, new[]{ "FrameIndex", "TimestampOffsetMs", "EchoArena" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nevr.Telemetry.V2.CaptureFooter), global::Nevr.Telemetry.V2.CaptureFooter.Parser, new[]{ "FrameCount", "DurationMs", "FooterOffset", "KeyframeIndex", "EventIndex" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nevr.Telemetry.V2.KeyframeEntry), global::Nevr.Telemetry.V2.KeyframeEntry.Parser, new[]{ "FrameIndex", "ByteOffset" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nevr.Telemetry.V2.EventIndexEntry), global::Nevr.Telemetry.V2.EventIndexEntry.Parser, new[]{ "EventType", "FrameIndices" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EventType {
    [pbr::OriginalName("EVENT_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("EVENT_TYPE_ROUND_STARTED")] RoundStarted = 1,
    [pbr::OriginalName("EVENT_TYPE_ROUND_PAUSED")] RoundPaused = 2,
    [pbr::OriginalName("EVENT_TYPE_ROUND_UNPAUSED")] RoundUnpaused = 3,
    [pbr::OriginalName("EVENT_TYPE_ROUND_ENDED")] RoundEnded = 4,
    [pbr::OriginalName("EVENT_TYPE_MATCH_ENDED")] MatchEnded = 5,
    [pbr::OriginalName("EVENT_TYPE_SCOREBOARD_UPDATED")] ScoreboardUpdated = 6,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_JOINED")] PlayerJoined = 10,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_LEFT")] PlayerLeft = 11,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_SWITCHED_TEAM")] PlayerSwitchedTeam = 12,
    [pbr::OriginalName("EVENT_TYPE_EMOTE_PLAYED")] EmotePlayed = 13,
    [pbr::OriginalName("EVENT_TYPE_DISC_POSSESSION_CHANGED")] DiscPossessionChanged = 20,
    [pbr::OriginalName("EVENT_TYPE_DISC_THROWN")] DiscThrown = 21,
    [pbr::OriginalName("EVENT_TYPE_DISC_CAUGHT")] DiscCaught = 22,
    [pbr::OriginalName("EVENT_TYPE_GOAL_SCORED")] GoalScored = 30,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_GOAL")] PlayerGoal = 31,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_SAVE")] PlayerSave = 40,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_STUN")] PlayerStun = 41,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_PASS")] PlayerPass = 42,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_STEAL")] PlayerSteal = 43,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_BLOCK")] PlayerBlock = 44,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_INTERCEPTION")] PlayerInterception = 45,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_ASSIST")] PlayerAssist = 46,
    [pbr::OriginalName("EVENT_TYPE_PLAYER_SHOT_TAKEN")] PlayerShotTaken = 47,
    [pbr::OriginalName("EVENT_TYPE_GENERIC")] Generic = 50,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Envelope : pb::IMessage<Envelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Envelope> _parser = new pb::MessageParser<Envelope>(() => new Envelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Envelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nevr.Telemetry.V2.CaptureReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope(Envelope other) : this() {
      switch (other.MessageCase) {
        case MessageOneofCase.Header:
          Header = other.Header.Clone();
          break;
        case MessageOneofCase.Frame:
          Frame = other.Frame.Clone();
          break;
        case MessageOneofCase.Footer:
          Footer = other.Footer.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope Clone() {
      return new Envelope(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nevr.Telemetry.V2.CaptureHeader Header {
      get { return messageCase_ == MessageOneofCase.Header ? (global::Nevr.Telemetry.V2.CaptureHeader) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.Header;
      }
    }

    /// <summary>Field number for the "frame" field.</summary>
    public const int FrameFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nevr.Telemetry.V2.Frame Frame {
      get { return messageCase_ == MessageOneofCase.Frame ? (global::Nevr.Telemetry.V2.Frame) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.Frame;
      }
    }

    /// <summary>Field number for the "footer" field.</summary>
    public const int FooterFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nevr.Telemetry.V2.CaptureFooter Footer {
      get { return messageCase_ == MessageOneofCase.Footer ? (global::Nevr.Telemetry.V2.CaptureFooter) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.Footer;
      }
    }

    private object message_;
    /// <summary>Enum of possible cases for the "message" oneof.</summary>
    public enum MessageOneofCase {
      None = 0,
      Header = 1,
      Frame = 2,
      Footer = 3,
    }
    private MessageOneofCase messageCase_ = MessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageOneofCase MessageCase {
      get { return messageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessage() {
      messageCase_ = MessageOneofCase.None;
      message_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Envelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Envelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (!object.Equals(Frame, other.Frame)) return false;
      if (!object.Equals(Footer, other.Footer)) return false;
      if (MessageCase != other.MessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (messageCase_ == MessageOneofCase.Header) hash ^= Header.GetHashCode();
      if (messageCase_ == MessageOneofCase.Frame) hash ^= Frame.GetHashCode();
      if (messageCase_ == MessageOneofCase.Footer) hash ^= Footer.GetHashCode();
      hash ^= (int) messageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (messageCase_ == MessageOneofCase.Header) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (messageCase_ == MessageOneofCase.Frame) {
        output.WriteRawTag(18);
        output.WriteMessage(Frame);
      }
      if (messageCase_ == MessageOneofCase.Footer) {
        output.WriteRawTag(26);
        output.WriteMessage(Footer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (messageCase_ == MessageOneofCase.Header) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (messageCase_ == MessageOneofCase.Frame) {
        output.WriteRawTag(18);
        output.WriteMessage(Frame);
      }
      if (messageCase_ == MessageOneofCase.Footer) {
        output.WriteRawTag(26);
        output.WriteMessage(Footer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (messageCase_ == MessageOneofCase.Header) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (messageCase_ == MessageOneofCase.Frame) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Frame);
      }
      if (messageCase_ == MessageOneofCase.Footer) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Footer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Envelope other) {
      if (other == null) {
        return;
      }
      switch (other.MessageCase) {
        case MessageOneofCase.Header:
          if (Header == null) {
            Header = new global::Nevr.Telemetry.V2.CaptureHeader();
          }
          Header.MergeFrom(other.Header);
          break;
        case MessageOneofCase.Frame:
          if (Frame == null) {
            Frame = new global::Nevr.Telemetry.V2.Frame();
          }
          Frame.MergeFrom(other.Frame);
          break;
        case MessageOneofCase.Footer:
          if (Footer == null) {
            Footer = new global::Nevr.Telemetry.V2.CaptureFooter();
          }
          Footer.MergeFrom(other.Footer);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Nevr.Telemetry.V2.CaptureHeader subBuilder = new global::Nevr.Telemetry.V2.CaptureHeader();
            if (messageCase_ == MessageOneofCase.Header) {
              subBuilder.MergeFrom(Header);
            }
            input.ReadMessage(subBuilder);
            Header = subBuilder;
            break;
          }
          case 18: {
            global::Nevr.Telemetry.V2.Frame subBuilder = new global::Nevr.Telemetry.V2.Frame();
            if (messageCase_ == MessageOneofCase.Frame) {
              subBuilder.MergeFrom(Frame);
            }
            input.ReadMessage(subBuilder);
            Frame = subBuilder;
            break;
          }
          case 26: {
            global::Nevr.Telemetry.V2.CaptureFooter subBuilder = new global::Nevr.Telemetry.V2.CaptureFooter();
            if (messageCase_ == MessageOneofCase.Footer) {
              subBuilder.MergeFrom(Footer);
            }
            input.ReadMessage(subBuilder);
            Footer = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Nevr.Telemetry.V2.CaptureHeader subBuilder = new global::Nevr.Telemetry.V2.CaptureHeader();
            if (messageCase_ == MessageOneofCase.Header) {
              subBuilder.MergeFrom(Header);
            }
            input.ReadMessage(subBuilder);
            Header = subBuilder;
            break;
          }
          case 18: {
            global::Nevr.Telemetry.V2.Frame subBuilder = new global::Nevr.Telemetry.V2.Frame();
            if (messageCase_ == MessageOneofCase.Frame) {
              subBuilder.MergeFrom(Frame);
            }
            input.ReadMessage(subBuilder);
            Frame = subBuilder;
            break;
          }
          case 26: {
            global::Nevr.Telemetry.V2.CaptureFooter subBuilder = new global::Nevr.Telemetry.V2.CaptureFooter();
            if (messageCase_ == MessageOneofCase.Footer) {
              subBuilder.MergeFrom(Footer);
            }
            input.ReadMessage(subBuilder);
            Footer = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CaptureHeader : pb::IMessage<CaptureHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CaptureHeader> _parser = new pb::MessageParser<CaptureHeader>(() => new CaptureHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CaptureHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nevr.Telemetry.V2.CaptureReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CaptureHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CaptureHeader(CaptureHeader other) : this() {
      captureId_ = other.captureId_;
      createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
      formatVersion_ = other.formatVersion_;
      metadata_ = other.metadata_.Clone();
      switch (other.GameHeaderCase) {
        case GameHeaderOneofCase.EchoArena:
          EchoArena = other.EchoArena.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CaptureHeader Clone() {
      return new CaptureHeader(this);
    }

    /// <summary>Field number for the "capture_id" field.</summary>
    public const int CaptureIdFieldNumber = 1;
    private string captureId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CaptureId {
      get { return captureId_; }
      set {
        captureId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    /// <summary>Field number for the "format_version" field.</summary>
    public const int FormatVersionFieldNumber = 3;
    private uint formatVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FormatVersion {
      get { return formatVersion_; }
      set {
        formatVersion_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 4;
    private static readonly pbc::MapField<string, string>.Codec _map_metadata_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 34);
    private readonly pbc::MapField<string, string> metadata_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Metadata {
      get { return metadata_; }
    }

    /// <summary>Field number for the "echo_arena" field.</summary>
    public const int EchoArenaFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nevr.Telemetry.V2.EchoArenaHeader EchoArena {
      get { return gameHeaderCase_ == GameHeaderOneofCase.EchoArena ? (global::Nevr.Telemetry.V2.EchoArenaHeader) gameHeader_ : null; }
      set {
        gameHeader_ = value;
        gameHeaderCase_ = value == null ? GameHeaderOneofCase.None : GameHeaderOneofCase.EchoArena;
      }
    }

    private object gameHeader_;
    /// <summary>Enum of possible cases for the "game_header" oneof.</summary>
    public enum GameHeaderOneofCase {
      None = 0,
      EchoArena = 10,
    }
    private GameHeaderOneofCase gameHeaderCase_ = GameHeaderOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameHeaderOneofCase GameHeaderCase {
      get { return gameHeaderCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGameHeader() {
      gameHeaderCase_ = GameHeaderOneofCase.None;
      gameHeader_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CaptureHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CaptureHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CaptureId != other.CaptureId) return false;
      if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
      if (FormatVersion != other.FormatVersion) return false;
      if (!Metadata.Equals(other.Metadata)) return false;
      if (!object.Equals(EchoArena, other.EchoArena)) return false;
      if (GameHeaderCase != other.GameHeaderCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CaptureId.Length != 0) hash ^= CaptureId.GetHashCode();
      if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
      if (FormatVersion != 0) hash ^= FormatVersion.GetHashCode();
      hash ^= Metadata.GetHashCode();
      if (gameHeaderCase_ == GameHeaderOneofCase.EchoArena) hash ^= EchoArena.GetHashCode();
      hash ^= (int) gameHeaderCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CaptureId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CaptureId);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CreatedAt);
      }
      if (FormatVersion != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(FormatVersion);
      }
      metadata_.WriteTo(output, _map_metadata_codec);
      if (gameHeaderCase_ == GameHeaderOneofCase.EchoArena) {
        output.WriteRawTag(82);
        output.WriteMessage(EchoArena);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CaptureId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CaptureId);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CreatedAt);
      }
      if (FormatVersion != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(FormatVersion);
      }
      metadata_.WriteTo(ref output, _map_metadata_codec);
      if (gameHeaderCase_ == GameHeaderOneofCase.EchoArena) {
        output.WriteRawTag(82);
        output.WriteMessage(EchoArena);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CaptureId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CaptureId);
      }
      if (createdAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
      }
      if (FormatVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FormatVersion);
      }
      size += metadata_.CalculateSize(_map_metadata_codec);
      if (gameHeaderCase_ == GameHeaderOneofCase.EchoArena) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EchoArena);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CaptureHeader other) {
      if (other == null) {
        return;
      }
      if (other.CaptureId.Length != 0) {
        CaptureId = other.CaptureId;
      }
      if (other.createdAt_ != null) {
        if (createdAt_ == null) {
          CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreatedAt.MergeFrom(other.CreatedAt);
      }
      if (other.FormatVersion != 0) {
        FormatVersion = other.FormatVersion;
      }
      metadata_.MergeFrom(other.metadata_);
      switch (other.GameHeaderCase) {
        case GameHeaderOneofCase.EchoArena:
          if (EchoArena == null) {
            EchoArena = new global::Nevr.Telemetry.V2.EchoArenaHeader();
          }
          EchoArena.MergeFrom(other.EchoArena);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CaptureId = input.ReadString();
            break;
          }
          case 18: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 24: {
            FormatVersion = input.ReadUInt32();
            break;
          }
          case 34: {
            metadata_.AddEntriesFrom(input, _map_metadata_codec);
            break;
          }
          case 82: {
            global::Nevr.Telemetry.V2.EchoArenaHeader subBuilder = new global::Nevr.Telemetry.V2.EchoArenaHeader();
            if (gameHeaderCase_ == GameHeaderOneofCase.EchoArena) {
              subBuilder.MergeFrom(EchoArena);
            }
            input.ReadMessage(subBuilder);
            EchoArena = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CaptureId = input.ReadString();
            break;
          }
          case 18: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 24: {
            FormatVersion = input.ReadUInt32();
            break;
          }
          case 34: {
            metadata_.AddEntriesFrom(ref input, _map_metadata_codec);
            break;
          }
          case 82: {
            global::Nevr.Telemetry.V2.EchoArenaHeader subBuilder = new global::Nevr.Telemetry.V2.EchoArenaHeader();
            if (gameHeaderCase_ == GameHeaderOneofCase.EchoArena) {
              subBuilder.MergeFrom(EchoArena);
            }
            input.ReadMessage(subBuilder);
            EchoArena = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Frame : pb::IMessage<Frame>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Frame> _parser = new pb::MessageParser<Frame>(() => new Frame());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Frame> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nevr.Telemetry.V2.CaptureReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Frame() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Frame(Frame other) : this() {
      frameIndex_ = other.frameIndex_;
      timestampOffsetMs_ = other.timestampOffsetMs_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.EchoArena:
          EchoArena = other.EchoArena.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Frame Clone() {
      return new Frame(this);
    }

    /// <summary>Field number for the "frame_index" field.</summary>
    public const int FrameIndexFieldNumber = 1;
    private uint frameIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FrameIndex {
      get { return frameIndex_; }
      set {
        frameIndex_ = value;
      }
    }

    /// <summary>Field number for the "timestamp_offset_ms" field.</summary>
    public const int TimestampOffsetMsFieldNumber = 2;
    private uint timestampOffsetMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimestampOffsetMs {
      get { return timestampOffsetMs_; }
      set {
        timestampOffsetMs_ = value;
      }
    }

    /// <summary>Field number for the "echo_arena" field.</summary>
    public const int EchoArenaFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nevr.Telemetry.V2.EchoArenaFrame EchoArena {
      get { return payloadCase_ == PayloadOneofCase.EchoArena ? (global::Nevr.Telemetry.V2.EchoArenaFrame) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.EchoArena;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      EchoArena = 10,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Frame);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Frame other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FrameIndex != other.FrameIndex) return false;
      if (TimestampOffsetMs != other.TimestampOffsetMs) return false;
      if (!object.Equals(EchoArena, other.EchoArena)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FrameIndex != 0) hash ^= FrameIndex.GetHashCode();
      if (TimestampOffsetMs != 0) hash ^= TimestampOffsetMs.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.EchoArena) hash ^= EchoArena.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrameIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(FrameIndex);
      }
      if (TimestampOffsetMs != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(TimestampOffsetMs);
      }
      if (payloadCase_ == PayloadOneofCase.EchoArena) {
        output.WriteRawTag(82);
        output.WriteMessage(EchoArena);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrameIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(FrameIndex);
      }
      if (TimestampOffsetMs != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(TimestampOffsetMs);
      }
      if (payloadCase_ == PayloadOneofCase.EchoArena) {
        output.WriteRawTag(82);
        output.WriteMessage(EchoArena);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FrameIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FrameIndex);
      }
      if (TimestampOffsetMs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimestampOffsetMs);
      }
      if (payloadCase_ == PayloadOneofCase.EchoArena) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EchoArena);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Frame other) {
      if (other == null) {
        return;
      }
      if (other.FrameIndex != 0) {
        FrameIndex = other.FrameIndex;
      }
      if (other.TimestampOffsetMs != 0) {
        TimestampOffsetMs = other.TimestampOffsetMs;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.EchoArena:
          if (EchoArena == null) {
            EchoArena = new global::Nevr.Telemetry.V2.EchoArenaFrame();
          }
          EchoArena.MergeFrom(other.EchoArena);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FrameIndex = input.ReadUInt32();
            break;
          }
          case 16: {
            TimestampOffsetMs = input.ReadUInt32();
            break;
          }
          case 82: {
            global::Nevr.Telemetry.V2.EchoArenaFrame subBuilder = new global::Nevr.Telemetry.V2.EchoArenaFrame();
            if (payloadCase_ == PayloadOneofCase.EchoArena) {
              subBuilder.MergeFrom(EchoArena);
            }
            input.ReadMessage(subBuilder);
            EchoArena = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FrameIndex = input.ReadUInt32();
            break;
          }
          case 16: {
            TimestampOffsetMs = input.ReadUInt32();
            break;
          }
          case 82: {
            global::Nevr.Telemetry.V2.EchoArenaFrame subBuilder = new global::Nevr.Telemetry.V2.EchoArenaFrame();
            if (payloadCase_ == PayloadOneofCase.EchoArena) {
              subBuilder.MergeFrom(EchoArena);
            }
            input.ReadMessage(subBuilder);
            EchoArena = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CaptureFooter : pb::IMessage<CaptureFooter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CaptureFooter> _parser = new pb::MessageParser<CaptureFooter>(() => new CaptureFooter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CaptureFooter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nevr.Telemetry.V2.CaptureReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CaptureFooter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CaptureFooter(CaptureFooter other) : this() {
      frameCount_ = other.frameCount_;
      durationMs_ = other.durationMs_;
      footerOffset_ = other.footerOffset_;
      keyframeIndex_ = other.keyframeIndex_.Clone();
      eventIndex_ = other.eventIndex_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CaptureFooter Clone() {
      return new CaptureFooter(this);
    }

    /// <summary>Field number for the "frame_count" field.</summary>
    public const int FrameCountFieldNumber = 1;
    private uint frameCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FrameCount {
      get { return frameCount_; }
      set {
        frameCount_ = value;
      }
    }

    /// <summary>Field number for the "duration_ms" field.</summary>
    public const int DurationMsFieldNumber = 2;
    private uint durationMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DurationMs {
      get { return durationMs_; }
      set {
        durationMs_ = value;
      }
    }

    /// <summary>Field number for the "footer_offset" field.</summary>
    public const int FooterOffsetFieldNumber = 3;
    private ulong footerOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong FooterOffset {
      get { return footerOffset_; }
      set {
        footerOffset_ = value;
      }
    }

    /// <summary>Field number for the "keyframe_index" field.</summary>
    public const int KeyframeIndexFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Nevr.Telemetry.V2.KeyframeEntry> _repeated_keyframeIndex_codec
        = pb::FieldCodec.ForMessage(34, global::Nevr.Telemetry.V2.KeyframeEntry.Parser);
    private readonly pbc::RepeatedField<global::Nevr.Telemetry.V2.KeyframeEntry> keyframeIndex_ = new pbc::RepeatedField<global::Nevr.Telemetry.V2.KeyframeEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Nevr.Telemetry.V2.KeyframeEntry> KeyframeIndex {
      get { return keyframeIndex_; }
    }

    /// <summary>Field number for the "event_index" field.</summary>
    public const int EventIndexFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Nevr.Telemetry.V2.EventIndexEntry> _repeated_eventIndex_codec
        = pb::FieldCodec.ForMessage(42, global::Nevr.Telemetry.V2.EventIndexEntry.Parser);
    private readonly pbc::RepeatedField<global::Nevr.Telemetry.V2.EventIndexEntry> eventIndex_ = new pbc::RepeatedField<global::Nevr.Telemetry.V2.EventIndexEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Nevr.Telemetry.V2.EventIndexEntry> EventIndex {
      get { return eventIndex_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CaptureFooter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CaptureFooter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FrameCount != other.FrameCount) return false;
      if (DurationMs != other.DurationMs) return false;
      if (FooterOffset != other.FooterOffset) return false;
      if(!keyframeIndex_.Equals(other.keyframeIndex_)) return false;
      if(!eventIndex_.Equals(other.eventIndex_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FrameCount != 0) hash ^= FrameCount.GetHashCode();
      if (DurationMs != 0) hash ^= DurationMs.GetHashCode();
      if (FooterOffset != 0UL) hash ^= FooterOffset.GetHashCode();
      hash ^= keyframeIndex_.GetHashCode();
      hash ^= eventIndex_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrameCount != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(FrameCount);
      }
      if (DurationMs != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(DurationMs);
      }
      if (FooterOffset != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(FooterOffset);
      }
      keyframeIndex_.WriteTo(output, _repeated_keyframeIndex_codec);
      eventIndex_.WriteTo(output, _repeated_eventIndex_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrameCount != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(FrameCount);
      }
      if (DurationMs != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(DurationMs);
      }
      if (FooterOffset != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(FooterOffset);
      }
      keyframeIndex_.WriteTo(ref output, _repeated_keyframeIndex_codec);
      eventIndex_.WriteTo(ref output, _repeated_eventIndex_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FrameCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FrameCount);
      }
      if (DurationMs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DurationMs);
      }
      if (FooterOffset != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(FooterOffset);
      }
      size += keyframeIndex_.CalculateSize(_repeated_keyframeIndex_codec);
      size += eventIndex_.CalculateSize(_repeated_eventIndex_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CaptureFooter other) {
      if (other == null) {
        return;
      }
      if (other.FrameCount != 0) {
        FrameCount = other.FrameCount;
      }
      if (other.DurationMs != 0) {
        DurationMs = other.DurationMs;
      }
      if (other.FooterOffset != 0UL) {
        FooterOffset = other.FooterOffset;
      }
      keyframeIndex_.Add(other.keyframeIndex_);
      eventIndex_.Add(other.eventIndex_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FrameCount = input.ReadUInt32();
            break;
          }
          case 16: {
            DurationMs = input.ReadUInt32();
            break;
          }
          case 24: {
            FooterOffset = input.ReadUInt64();
            break;
          }
          case 34: {
            keyframeIndex_.AddEntriesFrom(input, _repeated_keyframeIndex_codec);
            break;
          }
          case 42: {
            eventIndex_.AddEntriesFrom(input, _repeated_eventIndex_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FrameCount = input.ReadUInt32();
            break;
          }
          case 16: {
            DurationMs = input.ReadUInt32();
            break;
          }
          case 24: {
            FooterOffset = input.ReadUInt64();
            break;
          }
          case 34: {
            keyframeIndex_.AddEntriesFrom(ref input, _repeated_keyframeIndex_codec);
            break;
          }
          case 42: {
            eventIndex_.AddEntriesFrom(ref input, _repeated_eventIndex_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class KeyframeEntry : pb::IMessage<KeyframeEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KeyframeEntry> _parser = new pb::MessageParser<KeyframeEntry>(() => new KeyframeEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<KeyframeEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nevr.Telemetry.V2.CaptureReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KeyframeEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KeyframeEntry(KeyframeEntry other) : this() {
      frameIndex_ = other.frameIndex_;
      byteOffset_ = other.byteOffset_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KeyframeEntry Clone() {
      return new KeyframeEntry(this);
    }

    /// <summary>Field number for the "frame_index" field.</summary>
    public const int FrameIndexFieldNumber = 1;
    private uint frameIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FrameIndex {
      get { return frameIndex_; }
      set {
        frameIndex_ = value;
      }
    }

    /// <summary>Field number for the "byte_offset" field.</summary>
    public const int ByteOffsetFieldNumber = 2;
    private ulong byteOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ByteOffset {
      get { return byteOffset_; }
      set {
        byteOffset_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as KeyframeEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(KeyframeEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FrameIndex != other.FrameIndex) return false;
      if (ByteOffset != other.ByteOffset) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FrameIndex != 0) hash ^= FrameIndex.GetHashCode();
      if (ByteOffset != 0UL) hash ^= ByteOffset.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrameIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(FrameIndex);
      }
      if (ByteOffset != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(ByteOffset);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrameIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(FrameIndex);
      }
      if (ByteOffset != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(ByteOffset);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FrameIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FrameIndex);
      }
      if (ByteOffset != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ByteOffset);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(KeyframeEntry other) {
      if (other == null) {
        return;
      }
      if (other.FrameIndex != 0) {
        FrameIndex = other.FrameIndex;
      }
      if (other.ByteOffset != 0UL) {
        ByteOffset = other.ByteOffset;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FrameIndex = input.ReadUInt32();
            break;
          }
          case 16: {
            ByteOffset = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FrameIndex = input.ReadUInt32();
            break;
          }
          case 16: {
            ByteOffset = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EventIndexEntry : pb::IMessage<EventIndexEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EventIndexEntry> _parser = new pb::MessageParser<EventIndexEntry>(() => new EventIndexEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EventIndexEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nevr.Telemetry.V2.CaptureReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventIndexEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventIndexEntry(EventIndexEntry other) : this() {
      eventType_ = other.eventType_;
      frameIndices_ = other.frameIndices_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventIndexEntry Clone() {
      return new EventIndexEntry(this);
    }

    /// <summary>Field number for the "event_type" field.</summary>
    public const int EventTypeFieldNumber = 1;
    private global::Nevr.Telemetry.V2.EventType eventType_ = global::Nevr.Telemetry.V2.EventType.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nevr.Telemetry.V2.EventType EventType {
      get { return eventType_; }
      set {
        eventType_ = value;
      }
    }

    /// <summary>Field number for the "frame_indices" field.</summary>
    public const int FrameIndicesFieldNumber = 2;
    private static readonly pb::FieldCodec<uint> _repeated_frameIndices_codec
        = pb::FieldCodec.ForUInt32(18);
    private readonly pbc::RepeatedField<uint> frameIndices_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> FrameIndices {
      get { return frameIndices_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EventIndexEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EventIndexEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventType != other.EventType) return false;
      if(!frameIndices_.Equals(other.frameIndices_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventType != global::Nevr.Telemetry.V2.EventType.Unspecified) hash ^= EventType.GetHashCode();
      hash ^= frameIndices_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventType != global::Nevr.Telemetry.V2.EventType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      frameIndices_.WriteTo(output, _repeated_frameIndices_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventType != global::Nevr.Telemetry.V2.EventType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      frameIndices_.WriteTo(ref output, _repeated_frameIndices_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventType != global::Nevr.Telemetry.V2.EventType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventType);
      }
      size += frameIndices_.CalculateSize(_repeated_frameIndices_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EventIndexEntry other) {
      if (other == null) {
        return;
      }
      if (other.EventType != global::Nevr.Telemetry.V2.EventType.Unspecified) {
        EventType = other.EventType;
      }
      frameIndices_.Add(other.frameIndices_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventType = (global::Nevr.Telemetry.V2.EventType) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            frameIndices_.AddEntriesFrom(input, _repeated_frameIndices_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventType = (global::Nevr.Telemetry.V2.EventType) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            frameIndices_.AddEntriesFrom(ref input, _repeated_frameIndices_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
